runtime: nodejs16

env_variables: 
  DB_KEY: 'abc'
  JWT_SECRET: '*****'

service: service1
# handlers:
  # - url: /(.*\..+)$
  #   static_files: build/\1
  #   upload: build/(.*\..+)$
  # # Catch all handler to index.html
  # - url: /.*
  #   static_files: dist/index.html
  #   upload: dist